### ISSUE TITLE
Conflicts with prettier

### ISSUE THREAD

**Issue by screendriver** [jdforsythe/vscode-add-new-line-to-files#1]
I openend an issue https://github.com/esbenp/prettier-vscode/issues/42 at the [prettier](https://github.com/esbenp/prettier-vscode) plugin.

Your plugin produces an endless loop in my `package.json` file when `prettier` is enabled. It seems that this issue will be produced by your plugin and should be fixed here.

Any help would be welcome.

**Comment by jdforsythe** [comment]
There is a built in setting now that renders the extension unnecessary.

https://github.com/Microsoft/vscode/issues/12076

**Comment by screendriver** [comment]
Thank you @jdforsythe! I didn't knew that 🎉

**Comment by aaronfranke** [comment]
@jdforsythe Which commit and/or PR fixed microsoft/vscode#12076? I can't comment there because it's locked.
